/* Generated By:JavaCC: Do not edit this line. AmberParserAllConstants.java */
package Wattos.Converters.Amber;

public interface AmberParserAllConstants {

  int EOF = 0;
  int EOL = 5;
  int NOT_EOL = 6;
  int DIGIT = 7;
  int LETTER = 8;
  int ALPHANUMERIC = 9;
  int WHITESPACE = 10;
  int NOT_WHITESPACE = 11;
  int OPTIONALWHITESPACE = 12;
  int POUND = 13;
  int DQUOTE = 14;
  int NOT_DQUOTE = 15;
  int SQUOTE = 16;
  int NOT_SQUOTE = 17;
  int ONE_CHAR_WORD = 18;
  int NOT_ONE_CHAR_WORD = 19;
  int RST = 20;
  int END = 21;
  int EQUAL = 22;
  int COMMA = 23;
  int NUMBER = 24;
  int IXPK = 25;
  int NXPK = 26;
  int IALTD = 27;
  int R1 = 28;
  int R2 = 29;
  int R3 = 30;
  int R4 = 31;
  int RK2 = 32;
  int RK3 = 33;
  int IR6 = 34;
  int IGR1 = 35;
  int IGR2 = 36;
  int IAT = 37;
  int IRESID = 38;
  int IDXX = 39;
  int JD1 = 40;
  int DOBS1 = 41;
  int DOBSL1 = 42;
  int DOBSU1 = 43;
  int DIJ1 = 44;
  int ATNAM = 45;
  int LPAREN = 46;
  int RPAREN = 47;
  int WORD = 48;
  int POUNDCOMMENT = 49;
  int ILLEGAL_CHAR = 50;
  int ILLEGAL_WORD = 51;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<EOL>",
    "<NOT_EOL>",
    "<DIGIT>",
    "<LETTER>",
    "<ALPHANUMERIC>",
    "<WHITESPACE>",
    "<NOT_WHITESPACE>",
    "<OPTIONALWHITESPACE>",
    "\"#\"",
    "\"\\\"\"",
    "<NOT_DQUOTE>",
    "\"\\\'\"",
    "<NOT_SQUOTE>",
    "<ONE_CHAR_WORD>",
    "<NOT_ONE_CHAR_WORD>",
    "\"&rst\"",
    "<END>",
    "\"=\"",
    "\",\"",
    "<NUMBER>",
    "\"ixpk\"",
    "\"nxpk\"",
    "\"ialtd\"",
    "\"r1\"",
    "\"r2\"",
    "\"r3\"",
    "\"r4\"",
    "\"rk2\"",
    "\"rk3\"",
    "\"ir6\"",
    "\"igr1\"",
    "\"igr2\"",
    "\"iat\"",
    "\"iresid\"",
    "<IDXX>",
    "<JD1>",
    "<DOBS1>",
    "<DOBSL1>",
    "<DOBSU1>",
    "<DIJ1>",
    "\"atnam\"",
    "\"(\"",
    "\")\"",
    "<WORD>",
    "<POUNDCOMMENT>",
    "<ILLEGAL_CHAR>",
    "<ILLEGAL_WORD>",
  };

}
