package Wattos.CloneWars.Gui;

import Wattos.Episode_II.Globals;
/*
 * WattosParameterPanel.java
 *
 * Created on April 5, 2006, 3:55 PM
 */

/**
 *
 * @author  jurgen
 */
public class WattosParameterPanel extends javax.swing.JPanel {
    
    /**
     * 
     */
    private static final long serialVersionUID = -4104656544114940811L;
    /** Creates new form WattosParameterPanel */
    public WattosParameterPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel5 = new javax.swing.JLabel();
        jTextFieldInputFile1 = new javax.swing.JTextField();
        jButtonOpen4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonOpen6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Message about chosen value when in error.");

        jTextFieldInputFile1.setEditable(false);
        jTextFieldInputFile1.setText(Globals.wattos_home_page+"/macros/SleepWithoutQuit.wcf");

        jButtonOpen4.setText("Help");
        jButtonOpen4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpen4ActionPerformed(evt);
            }
        });

        jLabel6.setText("Examples:");

        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Enter url below or find existing file on local filesystems by button below");

        jLabel8.setText("Prompt:");

        jButtonOpen6.setText("Enter File");
        jButtonOpen6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpen6ActionPerformed(evt);
            }
        });

        jLabel9.setText("Enter Url:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { Globals.wattos_home_page+"/macros/SleepWithoutQuit.wcf", "C:\\my\\Wattos\\macros\\QuitBeforeBegun.wcf", "/share/my/Wattos/macros/QuitBeforeBegun.wcf" }));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonOpen6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonOpen4))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel8)
                            .add(jLabel6)
                            .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextFieldInputFile1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                            .add(jComboBox3, 0, 434, Short.MAX_VALUE)
                            .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {jLabel6, jLabel8, jLabel9}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(jLabel7))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(jComboBox3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(jTextFieldInputFile1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonOpen4)
                    .add(jButtonOpen6)
                    .add(jLabel5))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOpen6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpen6ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonOpen6ActionPerformed

    private void jButtonOpen4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpen4ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonOpen4ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOpen4;
    private javax.swing.JButton jButtonOpen6;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldInputFile1;
    // End of variables declaration//GEN-END:variables
    
}
