/* Generated By:JavaCC: Do not edit this line. XplorParserAllConstants.java */
package Wattos.Converters.Xplor;

public interface XplorParserAllConstants {

  int EOF = 0;
  int EOL = 5;
  int NOT_EOL = 6;
  int DIGIT = 7;
  int LETTER = 8;
  int ALPHANUMERIC = 9;
  int WHITESPACE = 10;
  int NOT_WHITESPACE = 11;
  int OPTIONALWHITESPACE = 12;
  int BANG = 13;
  int DOLLAR = 14;
  int DQUOTE = 15;
  int NOT_DQUOTE = 16;
  int END = 17;
  int REMARK = 18;
  int SET = 19;
  int ONE_CHAR_WORD = 20;
  int NOT_ONE_CHAR_WORD = 21;
  int WORD = 22;
  int LCURLY = 23;
  int RCURLY = 24;
  int NOT_CURLY = 25;
  int ASSI = 26;
  int SEGI = 27;
  int RESI = 28;
  int RESN = 29;
  int NAME = 30;
  int ATOM = 31;
  int AND = 32;
  int OR = 33;
  int PEAK = 34;
  int VOLUME = 35;
  int WEIGHT = 36;
  int SPECTRUM = 37;
  int HPM1 = 38;
  int HPM2 = 39;
  int PPM1 = 40;
  int PPM2 = 41;
  int CV = 42;
  int LPAREN = 43;
  int RPAREN = 44;
  int EQUAL = 45;
  int NUMBER = 46;
  int XPLOR_SYMBOL = 47;
  int IDENTIFIER = 48;
  int SPACEINLINE = 49;
  int BANGCOMMENT = 50;
  int REMARKCOMMENT = 51;
  int SETCOMMENT = 52;
  int CURLYCOMMENT = 53;
  int ILLEGAL_CHAR = 57;
  int ILLEGAL_WORD = 58;

  int DEFAULT = 0;
  int CURLY_STATE = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<EOL>",
    "<NOT_EOL>",
    "<DIGIT>",
    "<LETTER>",
    "<ALPHANUMERIC>",
    "<WHITESPACE>",
    "<NOT_WHITESPACE>",
    "<OPTIONALWHITESPACE>",
    "\"!\"",
    "\"$\"",
    "\"\\\"\"",
    "<NOT_DQUOTE>",
    "\"end\"",
    "<REMARK>",
    "\"set\"",
    "<ONE_CHAR_WORD>",
    "<NOT_ONE_CHAR_WORD>",
    "<WORD>",
    "\"{\"",
    "\"}\"",
    "<NOT_CURLY>",
    "<ASSI>",
    "<SEGI>",
    "<RESI>",
    "<RESN>",
    "\"name\"",
    "\"atom\"",
    "\"and\"",
    "\"or\"",
    "\"peak\"",
    "<VOLUME>",
    "<WEIGHT>",
    "<SPECTRUM>",
    "\"hpm1\"",
    "\"hpm2\"",
    "\"ppm1\"",
    "\"ppm2\"",
    "\"cv\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "<NUMBER>",
    "<XPLOR_SYMBOL>",
    "<IDENTIFIER>",
    "<SPACEINLINE>",
    "<BANGCOMMENT>",
    "<REMARKCOMMENT>",
    "<SETCOMMENT>",
    "<CURLYCOMMENT>",
    "<token of kind 54>",
    "<token of kind 55>",
    "<token of kind 56>",
    "<ILLEGAL_CHAR>",
    "<ILLEGAL_WORD>",
  };

}
