/* Generated By:JavaCC: Do not edit this line. EmbossParserAllConstants.java */
package Wattos.Converters.Emboss;

public interface EmbossParserAllConstants {

  int EOF = 0;
  int NOT_EOL = 5;
  int DIGIT = 6;
  int LETTER = 7;
  int ALPHANUMERIC = 8;
  int WHITESPACE = 9;
  int NOT_WHITESPACE = 10;
  int OPTIONALWHITESPACE = 11;
  int EOL = 12;
  int NUMBER = 13;
  int WORD = 14;
  int SEMICOLONCOMMENT = 15;
  int ILLEGAL_CHAR = 16;
  int ILLEGAL_WORD = 17;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<NOT_EOL>",
    "<DIGIT>",
    "<LETTER>",
    "<ALPHANUMERIC>",
    "<WHITESPACE>",
    "<NOT_WHITESPACE>",
    "<OPTIONALWHITESPACE>",
    "<EOL>",
    "<NUMBER>",
    "<WORD>",
    "<SEMICOLONCOMMENT>",
    "<ILLEGAL_CHAR>",
    "<ILLEGAL_WORD>",
  };

}
