/* Generated By:JavaCC: Do not edit this line. DiscoverParserAllConstants.java */
package Wattos.Converters.Discover;

public interface DiscoverParserAllConstants {

  int EOF = 0;
  int NOT_EOL = 5;
  int DIGIT = 6;
  int LETTER = 7;
  int ALPHANUMERIC = 8;
  int WHITESPACE = 9;
  int NOT_WHITESPACE = 10;
  int OPTIONALWHITESPACE = 11;
  int POUND = 12;
  int BANG = 13;
  int NOT_DQUOTE = 14;
  int ONE_CHAR_WORD = 15;
  int NOT_ONE_CHAR_WORD = 16;
  int SPACEINLINE = 17;
  int SIGN = 18;
  int ATOM_ID = 19;
  int NUMBER = 20;
  int PLUS = 21;
  int NAME = 22;
  int POUNDCOMMENT = 23;
  int ILLEGAL_CHAR = 24;
  int ILLEGAL_WORD = 25;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<NOT_EOL>",
    "<DIGIT>",
    "<LETTER>",
    "<ALPHANUMERIC>",
    "<WHITESPACE>",
    "<NOT_WHITESPACE>",
    "<OPTIONALWHITESPACE>",
    "\"#\"",
    "\"!\"",
    "<NOT_DQUOTE>",
    "<ONE_CHAR_WORD>",
    "<NOT_ONE_CHAR_WORD>",
    "<SPACEINLINE>",
    "<SIGN>",
    "<ATOM_ID>",
    "<NUMBER>",
    "\"+\"",
    "<NAME>",
    "<POUNDCOMMENT>",
    "<ILLEGAL_CHAR>",
    "<ILLEGAL_WORD>",
  };

}
